version: "3.9"

services:
  portfolio:
    image: nginx:alpine
    container_name: portfolio_site
    ports:
      - "4500:80"   # change 4500 to any port you want
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
